<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Car;

class CarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'model_id' => 1,
                'dealer_id' => 1,
                'vehicle_identification_number' => '1HGCM82633A123401',
                'car_type_id' => 1,
                'price' => 250000,
                'fuel_type_id' => 1,
                'transmission_type_id' => 2,
                'car_seater_id' => 1,
                'safety_rating' => 3,
                'tax' => 1200,
                'mileage' => 15,
                'discount' => 500,
                'like_count' => 100,
                'is_available' => true,
            ],
            [
                'model_id' => 2,
                'dealer_id' => 1,
                'vehicle_identification_number' => '2FZHAZBD61AH45602',
                'car_type_id' => 2,
                'price' => 300000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 2,
                'safety_rating' => 4,
                'tax' => 1500,
                'mileage' => 12,
                'discount' => null,
                'like_count' => 50,
                'is_available' => true,
            ],
            [
                'model_id' => 3,
                'dealer_id' => 1,
                'vehicle_identification_number' => '3C7WRTCL6EG456703',
                'car_type_id' => 3,
                'price' => 450000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 3,
                'safety_rating' => 5,
                'tax' => 2000,
                'mileage' => 10,
                'discount' => 1000,
                'like_count' => 75,
                'is_available' => true,
            ],
            [
                'model_id' => 4,
                'dealer_id' => 1,
                'vehicle_identification_number' => '3C7WRTCL6EG456704',
                'car_type_id' => 4,
                'price' => 420000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 3,
                'safety_rating' => 5,
                'tax' => 2000,
                'mileage' => 10,
                'discount' => 1000,
                'like_count' => 75,
                'is_available' => true,
            ],
            #2
            [
                'model_id' => 1,
                'dealer_id' => 2,
                'vehicle_identification_number' => '1HGCM82633A123405',
                'car_type_id' => 1,
                'price' => 250000,
                'fuel_type_id' => 1,
                'transmission_type_id' => 2,
                'car_seater_id' => 1,
                'safety_rating' => 3,
                'tax' => 1200,
                'mileage' => 15,
                'discount' => 500,
                'like_count' => 100,
                'is_available' => true,
            ],
            [
                'model_id' => 2,
                'dealer_id' => 2,
                'vehicle_identification_number' => '2FZHAZBD61AH45606',
                'car_type_id' => 2,
                'price' => 300000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 2,
                'safety_rating' => 4,
                'tax' => 1500,
                'mileage' => 12,
                'discount' => null,
                'like_count' => 50,
                'is_available' => true,
            ],
            [
                'model_id' => 3,
                'dealer_id' => 2,
                'vehicle_identification_number' => '3C7WRTCL6EG456707',
                'car_type_id' => 3,
                'price' => 450000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 3,
                'safety_rating' => 5,
                'tax' => 2000,
                'mileage' => 10,
                'discount' => 1000,
                'like_count' => 75,
                'is_available' => true,
            ],
            [
                'model_id' => 4,
                'dealer_id' => 2,
                'vehicle_identification_number' => '3C7WRTCL6EG456708',
                'car_type_id' => 4,
                'price' => 420000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 3,
                'safety_rating' => 5,
                'tax' => 2000,
                'mileage' => 10,
                'discount' => 1000,
                'like_count' => 75,
                'is_available' => true,
            ],
            #3
            [
                'model_id' => 1,
                'dealer_id' => 3,
                'vehicle_identification_number' => '1HGCM82633A123409',
                'car_type_id' => 1,
                'price' => 250000,
                'fuel_type_id' => 1,
                'transmission_type_id' => 2,
                'car_seater_id' => 1,
                'safety_rating' => 3,
                'tax' => 1200,
                'mileage' => 15,
                'discount' => 500,
                'like_count' => 100,
                'is_available' => true,
            ],
            [
                'model_id' => 2,
                'dealer_id' => 3,
                'vehicle_identification_number' => '2FZHAZBD61AH45610',
                'car_type_id' => 2,
                'price' => 300000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 2,
                'safety_rating' => 4,
                'tax' => 1500,
                'mileage' => 12,
                'discount' => null,
                'like_count' => 50,
                'is_available' => true,
            ],
            [
                'model_id' => 3,
                'dealer_id' => 3,
                'vehicle_identification_number' => '3C7WRTCL6EG456711',
                'car_type_id' => 3,
                'price' => 450000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 3,
                'safety_rating' => 5,
                'tax' => 2000,
                'mileage' => 10,
                'discount' => 1000,
                'like_count' => 75,
                'is_available' => true,
            ],
            [
                'model_id' => 4,
                'dealer_id' => 3,
                'vehicle_identification_number' => '3C7WRTCL6EG456712',
                'car_type_id' => 4,
                'price' => 420000,
                'fuel_type_id' => 2,
                'transmission_type_id' => 1,
                'car_seater_id' => 3,
                'safety_rating' => 5,
                'tax' => 2000,
                'mileage' => 10,
                'discount' => 1000,
                'like_count' => 75,
                'is_available' => true,
            ]
        ];

        foreach ($cars as $car) {
            Car::create($car);
        }
    }
}
